### ISSUE TITLE
Look into Dash as a shiny alternative for Python

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#12]
https://dash.plot.ly/

**Comment by manilevian** [comment]
I had a quick look into it and it seems very fluent and does everything which shiny does too. 
I might try to implement it into my Instagram App for testing purposes! 

There are a lot of preprogrammed Dashboards which you can also choose from instead of creating your own. Dash is completely equal to Shiny and isn't missing any features you'd wish for.
