### ISSUE TITLE
Platform priority list?

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#18]
See #8

**Comment by manilevian** [comment]
In the prior Issue my intention was looking at the amount of users that every social Network has. I used [this chart](https://www.statista.com/statistics/272014/global-social-networks-ranked-by-number-of-users/) for my evaluation. Apparently I did not have a premium account at statista to be able to see, how the numbers were evaluated and why couple of Asian and Russian Networks are not popping up in that chart! However I continued removing Mobile and non English Networks which gave me this Output: 

**Webbased:** 
I bolded those who are actually mobile apps, but also have desktop solutions

**WeChat**
**TikTok**
Reddit
LinkedIn
Printerest

**Mobile Apps:** 
(WhatsApp)
(FB Messanger)
SnapChat
Telegram (Not on the Statista Site, 200mil Users by feb. 2016) 

My personal thoughts are also: The number of users doesn’t mirror the "importance" of a social Network. I would say f.e., that Telegram has a higher priority than LinkedIn and Printerest. I guess it also depends on the type of research you are aiming for. Since minors are easily using more discord (Which you wont find in the list above), WeChat and similar and adults will be found more on one of the other platform, like reddit or linkedIn. 

Considering these arguments my prio list would look like this:

Reddit
TikTok
snapchat
WeChat
telegram
discord
Twitch

Why i removed Printerest and LinkedIn:
personally they don’t have a high value of research within our realm. LinkedIn is concentrated on business relations and similar. Less family or political motivated actions. Maybe I am completely wrong. As you know I am still not really into this as you are. So please prove me wrong if so ;)!!

So far ;)

**Comment by FlxVctr** [comment]
@manilevian do we still do this or can we close/postpone this? I'd like to close the milestone.

**Comment by manilevian** [comment]
Ofc. we can focus on what we have to clear out now. So its really okay to postpone this. Also we have a lot of new emerging exciting social networks which we will need to evaluate later on!

feel free to close ;)!
