### ISSUE TITLE
Adding "About Webscraping" to Wiki!

### ISSUE THREAD

**Issue by manilevian** [Leibniz-HBI/Social-Media-Observatory#19]
I thought about a wikipage, which introduces people to Web Scraping and specially shows the limitations and possibilities. This could also be solved with a FAQ. I am not sure what the best solution is. Any thoughts?

**Comment by FlxVctr** [comment]
I would start with a general FAQ or a Glossary that deals with all kinds of terms that might need some explanation for some readers. It it is less of an effort. We can then extend single terms/questions from that to a whole page when deemed necessary.

**Comment by FlxVctr** [comment]
Actually, I'd start with a glossary and have FAQ when we get actual questions more often.

**Comment by manilevian** [comment]
Hey i created a google doc to gather as many terms as possible. After that, we can filter what really needs a definition or not. For now just don’t think too much about "Do we really need this?", just put it where it belongs and we'll think about the importance later.

[Here the Link to the Doc](https://docs.google.com/document/d/1eX5Vx_R3-Glxcr0LMp_XxRi0nxtAgZ80keHWFoW1HZ0/edit?usp=sharing)

**Comment by FlxVctr** [comment]
Hm, I'd rather save the time and only explain words on a needs-basis (such as web scraping). Maybe your first idea was actually the best. Create a Wiki Page "Web Scraping", maybe also just as a stub, or link to a good explanation somewhere else, if we feel that a term may need some explanation.

**Comment by FlxVctr** [comment]
That enables us to just, in classical wiki manner, create a dead link [[to something]] while writing.

**Comment by Khandoker09** [comment]
# Web scrapping:

It’s a process of extracting data or information from a website and turn that information’s into a useful format for further analysis. A Typical process of web scraping is, first fetch the target webpage then parse information from that page. Next format the information into a useful format and then store then in a database or server for further analysis.

## Web scraper:

A web scraper is a computer programmer or software which can be used for web scraping.  A web scraper contains a crawler and a scraper. Crawler is algorithms or AI which is build to browse particular data from a website. On the other hand, ther scraper is the tool that is created to extract data from a website. So when a scraper needs to scrape data from a website, first the URLs of the website are provided. Then it loads the HTML code which is written to design the site or CSS code and javascript elements depending on the ability of the scraper. Next, the scraper extracts the data from HTML and saves the data in a useful format. Most scraper use CSV, Excel, or JSON to save the data.

### Advantages of web scraping:

* Unique, rich, and independent datasets can be achieved by using a scraper. Don’t have to depend on any third party to get the data that is required.

* Instead of copying and pasting data from the internet or buying data from a third party, we can choose what data we want to collect and store them in a local server or cloud for further analysis.

* Automation can be achieved by using the web scraper. We can run the scraper on daily basis and collect the specific data for every day and store them which can save.

### Disadvantages of web scraping:

* Building a scraper might require lots of programming knowledge. Otherwise, build in scraping software can be used to scrape which might cost depending on the tools. Also using third-party software can create limitations on required scraping data.

* Website changes their structure regularly which required a great deal of maintenance.

* Also, scaping a website means using their resources so the best practice would be respectful and avoid plagiarism and set a gentle request rate limit. Also, should ask permission when storing personal data that is sensitive. 

 

### Useful open source scrapers:

In this case, we prioritize the tools which are open source and have a GUI, lastly required less programming. 

#### [Facepager](https://github.com/strohne/Facepager/) :

Facepager is a useful open-source software that can scrap data from Youtube, Twitter, or other websites based on API. It has its own GUI which is very useful for a person who does not have any programming background. 

#### [Scrapy](https://github.com/scrapy/scrapy) :

Scrapy is a strong web crawler and scraper which can be used to scrape data from a website and then store the data in a structured way. However, scrapy a required little bit of python programming knowledge.

#### [Heritrix](https://webarchive.jira.com/wiki/spaces/Heritrix/overview) :

Heritrix  is a java based open-source scraper which provides a user interface with a web browser to operate the crawler. Heritrix required a strong programming background, so it’s not for the beginners

**Comment by FlxVctr** [comment]
Can you post that in a Google Doc or similar? That will make working on it easier.

**Comment by Khandoker09** [comment]
https://docs.google.com/document/d/1LU0JRvxSsykstQxsk0rdgIzSkffxfcR_6DiPyEjFopE/edit?usp=sharing

**Comment by FlxVctr** [comment]
I've added suggestions and comments to the GDoc.
