### ISSUE TITLE
Evaluate Grafana as a Tableau alternative

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#50]
https://grafana.com/

**Comment by manilevian** [comment]
Hey,

I took a week of getting into Tableau and was working on a side project with Grafana and got to know both a bit better. Tableau although, I must admit, not as deep as Grafana so my conclusion MIGHT be biased!! :D

The main factors leading to Grafana being the "better" solution might be pricing and the fact that Grafana works magnificent with multiple data points. Tableau works rather bad with a lot of data points. Meaning, realtime data experience is not great. 

Whereas Tableau is easy to use and has a lot of build in tweaks, making a quick and easy visualization really quaint, even for unexperienced users. 
Grafana has the same features but it is harder for a non-dev to get into it quickly. Once your into it, Grafana is beautiful and builds endless opportunities to visualize your data from endless API’s, Scraped Data and archives. 

Tableau is ‚kind of‘ free to use (Tableau Public) and costs money for most of the other apps. Grafana is completely open source and has an enterprise solution, which they sell in a monthly base. Tableau ofc has that too, but is very pricey compared to Grafana. 

Among the „BI“ community Grafana has a high recognition and is very often named when it comes to this topic. Tableau is always mentioned, but also it’s lack of „style“ and real time data visualization.   My conclusion:

If we are looking forward to build our own visualization f.e. Twitter API and connect that to a variety of API’s and visualize it live in one dashboard, we should use Grafana. For the simple reason, that it works without problems in real time and can connect to all sorts of containers and visualize every data from every source seamless ;)!! You can even use it to monitor multiple scraper instances than you are running for a project and get alerted if something goes wrong while drinking a good drink outside of your dashboard. These possibilities are not given with Tableau (as far as I understood)

Building quick and usable applications for other researchers with little tutorials and such, could be done with Tableau. Doing this with Grafana might end up in very time consuming work, since Grafana is a bit more complex than Tableau. Also as a reference for data visualization I would also recommend Tableau to others. For anyone who is eager to learn more or is some sort of experience user, I would also think about recommending Grafana. But on the argument of building easy to understand tutorials for our wiki f.e. I would really would use Tableau, since an every day researcher is able to learn it. 

For us it makes simply more sense to work with Grafana since its variety is way higher for our use range. It is worthwhile to learn on a long term and can benefit us on multiple sides of the project!

So far!

**Comment by FlxVctr** [comment]
Thanks, this seems a sound way to go forward!

**Comment by FlxVctr** [comment]
We should add both tools to our Analysis Tools list.
