### ISSUE TITLE
Add MeetUp to observed platforms long-term?

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#8]
It has a pretty open API and becomes more and more popular for offline networking.

**Comment by manilevian** [comment]
I checked out Meetup a bit. Indeed the API is very open, but we have to consider these facts about them:

1. They "only" have 35mil users by 2017
2. They charge their Users 24$/month for creating groups and similar. Which slows down growth.
3. Facebook has just renewed their group functions to compete with meetup (They ofc. charge nothing but your data ;))
4. The owner is WeWork, which I assume, you also know is a pretty greedy company!
5. In order to use the API, you have to be a paying customer. Thats at least how I understood them. Also this dev. stopped programming because of that, see his readme: https://github.com/rdohms/meetup-api-client

We should most definitely keep an eye on meetup. For now, its just a small amount of users using meetup and therefore I would rather priories the following first and whenever we are done with this List, we can head to meetup: 

Reddit, LinkedIn, Youtube, (Twitch)

and mobile chatting apps like:
telegram, WeChat, TikTok, (Snapchat, LINE, discord) 

That would be my idea. Maybe we should make a prio list :)

**Comment by FlxVctr** [comment]
Well, we already have the platforms that are part of the original proposal. But we could rethink this during our meeting in January when we want to decide on milestones.

I like the idea of a priority list for the more elaborated concept of the SMO. We should discuss that.
